### ISSUE TITLE
merged cell

### ISSUE THREAD

**Issue by linlexing** [tealeg/xlsx#102]
Do not see how to read and write the merged cell.Such as：

<table>
<tr><td>A</td><td>B</td></tr>
<tr><td colspan=2 align=center>C</td></tr>
</table>

at (https://github.com/SheetJS/js-xlsx)
>ws['!merges']: array of range objects corresponding to the merged cells in the worksheet. Plaintext utilities are unaware of merge cells. CSV export will write all cells in the merge range if they exist, so be sure that only the first cell (upper-left) in the range is set.

but not found read and write the merged cell at this project.

**Comment by ShawnMilo** [comment]
Please provide more detail, including a sample spreadsheet and a step-by-step description of what you are trying to do and how it's behaving differently than you expect it to.

**Comment by PowerTap** [comment]
I agree with @linlexing using the spreadsheet: https://docs.google.com/spreadsheets/d/1cS3Ut6kDOHyVB92wjK-WkwEXLv4kE-8YtdPCpKUqCQg/edit?usp=sharing

If I query sheet(1).Cells(0,0).Value I get a value of "".  I would hope to get a value of "Value A".

**Comment by ShawnMilo** [comment]
I downloaded the document from Google Spreadsheets as a .xlsx file. Reading with this package, I get two rows. The first has one cell containing `Value A` and the second has two cells with `Value B` and `Value C`. Is this fixed in the current version?

If not, please provide a spreadsheet which demonstrates the problem I can download directly; perhaps the Google export did something to it which masks the problem.

**Comment by ShawnMilo** [comment]
@linlexing @PowerTap 

We just merged PR #110. Please let me know if this issue has been fixed. If not, please see my last comment about providing a sample spreadsheet.

**Comment by fshiori** [comment]
It seems only solve write problem, but still not at read file.
I can't find any method to get merged cells info when reading file, and Cell.HMerge/VMerge is always 0.

**Comment by tealeg** [comment]
I think I understand.  The problem is not getting the value of the cell (which is stored in A1) but in knowing that A1 and B1 are merged.

**Comment by tealeg** [comment]
As of now you should be able to read valid values of Cell.HMerge and Cell.VMerge.
